"""Report generation utilities for the Omniscient Architect."""

from typing import Dict, Any
from .models import ReviewResult


class ReportGenerator:
    """Generates formatted reports from analysis results."""

    def generate_markdown_report(self, result: ReviewResult) -> str:
        """Generate a comprehensive markdown report."""
        lines = []

        # Header
        lines.extend([
            "# 🧠 Omniscient Architect - AI Code Review Report",
            "",
            "---",
            ""
        ])

        # Executive Summary
        lines.extend([
            "## 1. 🎯 Executive Summary & Alignment Check",
            "",
            "### Project Understanding:",
            result.project_understanding,
            "",
            f"### Goal Alignment Score: {result.goal_alignment_score}%",
            "",
            "### Component Breakdown:",
        ])

        for component, status in result.component_status.items():
            lines.append(f"  • {component}: {status}")
        lines.append("")

        # Strengths
        if result.strengths:
            lines.extend([
                "## 2. 💪 Strengths (With Evidence)",
                ""
            ])

            for strength in result.strengths:
                lines.extend([
                    f"**Strength:** {strength['strength']}",
                    f"**Evidence:** {strength['evidence']}",
                    f"**Why it matters:** {strength['why_it_matters']}",
                    ""
                ])

        # Critical Review
        if any(result.weaknesses.values()):
            lines.extend([
                "## 3. ⚠️ Critical Review: Weaknesses & Adjustments",
                ""
            ])

            for category, issues in result.weaknesses.items():
                if issues:
                    lines.append(f"### {category}:")
                    lines.append("")
                    for issue in issues:
                        lines.extend([
                            f"**Issue:** {issue['issue']}",
                            f"**Location:** {issue['location']}",
                            f"**The Fix:** {issue['fix']}",
                            ""
                        ])

        # Strategic Advice
        if result.strategic_advice:
            lines.extend([
                "## 4. 🧠 The Strategist's Advisor",
                "",
                "### Scalability:",
                result.strategic_advice['scalability'],
                "",
                "### Future-Proofing:",
                result.strategic_advice['future_proofing'],
                "",
                "### Broader Application:",
                result.strategic_advice['broader_application'],
                ""
            ])

        # AI Insights
        if result.ai_insights:
            lines.extend([
                "## 5. 🤖 AI Analysis Insights",
                "",
                "### Agent Confidence Levels:",
            ])

            for agent, confidence in result.ai_insights.get('agent_confidence', {}).items():
                lines.append(f"  • {agent}: {confidence:.2f}")

            if result.ai_insights.get('key_themes'):
                lines.extend([
                    "",
                    "### Key Themes Identified:",
                ])
                for theme in result.ai_insights['key_themes']:
                    lines.append(f"  • {theme}")

            lines.append("")

        # Footer
        lines.extend([
            "---",
            "",
            "*Report generated by Omniscient Architect - AI-powered code analysis*",
            ""
        ])

        return "\n".join(lines)

    def generate_json_report(self, result: ReviewResult) -> Dict[str, Any]:
        """Generate a structured JSON report."""
        return {
            "project_understanding": result.project_understanding,
            "goal_alignment_score": result.goal_alignment_score,
            "component_status": result.component_status,
            "strengths": result.strengths,
            "weaknesses": result.weaknesses,
            "strategic_advice": result.strategic_advice,
            "ai_insights": result.ai_insights,
            "metadata": {
                "version": "0.2.0",
                "generator": "Omniscient Architect"
            }
        }